EstimateMyApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/urls.py
from . import views
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views

app_name = "app"

urlpatterns = [

    # /app/
    # path("", views.IndexView.as_view(), name="index"),
    path("", views.index, name="index"),


    # /app/about/
    path("about/", views.AboutView.as_view(), name="about"),

    # /app/11/
    path("<int:pk>/", views.DetailView.as_view(), name="album_info"),

    # /app/11/favorite/
    #path("<int:album_id>/favorite/", views.favorite, name="favorite"),

    # /app/login/
    # path("login/$", auth_views.login, name='login'),
    path("login/", auth_views.login, {'template_name': 'app/login.html'}, name='login'),

    # /app/logout/
    # path("logout/$", auth_views.logout, name='logout'),
    path("logout/", auth_views.logout, {'template_name': 'app/about.html'}, name='logout'),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

app/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + " - " + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

app/views.py
"""from django.shortcuts import render, get_object_or_404
from . models import Album, Song


def index(request):
    all_albums = Album.objects.all()
    return render(request, "app/index.html", {"all_albums": all_albums})


def about(request):
    return render(request, "app/about.html")


def album_info(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, "app/album_info.html", {"album": album})


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST["song"])
    except (KeyError, Song.DoesNotExist):
        return render(request, "app/album_info.html", {
            "album": album,
            "error_message": "You did not select a valid song",
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, "app/album_info.html", {"album": album})"""



from django.views import generic

from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from . models import Album, Song
from . serializers import AlbumSerializer

from django.shortcuts import render

"""def index(request):
    username = None
    if request.user.is_authenticated():
        username = request.user.username

    return render(request, "app/index.html", {"username": username})"""


class AlbumList(APIView):

    def get(self, request):
        albums = Album.objects.all()
        serializer = AlbumSerializer(albums, many=True)
        return Response(serializer.data)


"""class IndexView(generic.View):
    def get(self, request):
        all_albums = Album.objects.all()
        username = None
        if request.user.is_authenticated:
            username = request.user.username

        return render(request, "app/index.html", {"username": username}, {"all_albums": all_albums})"""


def index(request):
    all_albums = Album.objects.all()
    username = None
    if request.user.is_authenticated:
        username = request.user.username

    return render(request, "app/index.html", {"username": username, "all_albums": all_albums})


"""class IndexView(generic.ListView):
    template_name = "app/index.html"

    def get_queryset(self):
        return Album.objects.all()"""

class DetailView(generic.DetailView):
    model = Album
    template_name = "app/album_info.html"

class AboutView(generic.TemplateView):
    template_name = "app/about.html"

app/templates/app/about.html
{% extends "app/base.html" %}

{% block body %}

<h3>About</h3>

<br>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eget ex sollicitudin, rutrum mauris consequat, maximus orci. Phasellus non lectus vitae diam maximus lobortis. Phasellus a arcu purus. Sed cursus ullamcorper arcu. Donec facilisis venenatis ultricies. Etiam vitae justo porttitor nisi tincidunt sodales in sed ante. Fusce vitae quam at ante efficitur aliquam vitae vitae eros. Donec eleifend massa in nisl interdum, nec molestie nulla dapibus. Proin tempus sem in ante consectetur, nec dignissim sem sodales. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla auctor, nunc eget facilisis posuere, ante nunc congue sapien, feugiat iaculis magna magna in augue.</p>

<p>Aenean vestibulum lacinia maximus. In hac habitasse platea dictumst. Phasellus dapibus odio vitae libero mollis gravida. Suspendisse ut sagittis metus, eu dignissim dui. Vestibulum nec feugiat metus, at luctus ligula. Vivamus vitae elit id eros tincidunt pulvinar. Etiam at felis ultricies, porttitor enim sagittis, egestas eros. Morbi fermentum malesuada risus, vel vehicula magna rhoncus ac. Suspendisse potenti.</p>

<p>Integer eget lorem ipsum. Maecenas congue elit quis nibh elementum tempus. Aliquam condimentum commodo ante id dapibus. Nunc leo nisi, molestie sed scelerisque at, venenatis nec elit. Fusce tempus urna imperdiet, gravida metus non, tincidunt arcu. In tellus ligula, semper at orci elementum, convallis iaculis nibh. Morbi massa augue, aliquam vitae sodales et, consectetur nec enim. Maecenas eleifend eros facilisis, facilisis lectus eget, tincidunt dolor. Aliquam euismod ipsum sed magna placerat hendrerit eu sed nisl. Proin sagittis neque eros, sit amet mollis nulla tempor ut. Nam sodales orci at mauris consequat venenatis. In consectetur orci a justo gravida, non ultrices dui fringilla. Fusce iaculis elementum nisi, non ultrices diam mattis a. Quisque eu mi ante. Curabitur ipsum odio, sodales a enim id, dignissim hendrerit nibh.</p>

{% endblock %}

app/templates/app/album_info.html
{% extends "app/base.html" %}

{% block body %}

<img src="{{ album.album_logo }}" width="220">

<h3>{{ album.album_title }}</h3>
<h4>{{ album.artist }}</h4>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

{% for song in album.song_set.all %}
    {{ song.song_title }}
    <br>
{% endfor %}

{% endblock %}

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static 'app/favicon.ico' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Title</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'app:index' %}">DjangoTest</a>
        <a class="navbar-brand" href="{% url 'app:about' %}">About</a>
        <a class="navbar-brand" href="{% url 'app:login' %}">Login</a>
        <a class="navbar-brand" href="{% url 'app:logout' %}">Logout</a>
        <a class="navbar-brand" href="{% url 'app:index' %}">{{ username }}</a>
    </nav>
    <div class="cont">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

app/templates/app/index.html
{% extends "app/base.html" %}

{% block body %}

<h3>Here are all my Albums:</h3>

<br>

{% if all_albums %}
    <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'app:album_info' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>There is nothing</h3>
{% endif %}

{% endblock %}

app/templates/app/login.html
{% extends "app/base.html" %}

{% block body %}

<h2>Login</h2>
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Login</button>
</form>

{% endblock %}